---
- name: create logs directory for root user
  file: path=/root/ansible/logs state=directory mode=0775

- name: create logs directory for vagrant user      
  file: path=/home/vagrant/ansible/logs state=directory mode=0775


- name: run ansible into vagrant-ansible machine
  #become_user: root
  #become: yes
  #local_action: command cd /home/vagrant/ansible/ && sudo ansible-playbook -i /home/vagrant/ansible/inventory /home/vagrant/ansible/setup.yml -vvv
  shell: "cd /home/vagrant/ansible/ && sudo ansible-playbook -i /home/vagrant/ansible/inventory /home/vagrant/ansible/setup.yml -vvv"

      
